
namespace NotePad
{
	[default_interface]
	runtimeclass WrapPanel : Windows.UI.Xaml.Controls.Panel
	{
		WrapPanel();
		Double HorizontalSpacing;
		Double VerticalSpacing;
		Windows.UI.Xaml.Controls.Orientation Orientation;
		Windows.UI.Xaml.Thickness Padding;

		static Windows.UI.Xaml.DependencyProperty HorizontalSpacingProperty{ get; };
		static Windows.UI.Xaml.DependencyProperty VerticalSpacingProperty{ get; };
		static Windows.UI.Xaml.DependencyProperty OrientationProperty{ get; };
		static Windows.UI.Xaml.DependencyProperty PaddingProperty{ get; };
	};
}